// app/layout.js
import React from 'react';

export const metadata = {
  title: 'Akosovski - Gaming',
  description: 'Generated by Next JS',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}