// MAIN
import Head from "next/head";
import * as React from 'react';
import { useState, useEffect } from "react";
import Image from "next/image";

// COMPONENTS

// SVG FILES

export default function Page() {
    const [darkMode, setDarkMode] = useState(false);
    return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Akosovski - Gaming</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="#" />
        </Head> 
        <h1>Hello, Testing!</h1>
      </div>
    )
  }